export type Role = "user" | "assistant" | "tool";

export interface ToolDefinition {
  name: string;
  description: string;
  input_schema: Record<string, unknown>;
}

export interface Message {
  role: Role;
  content: string | MessageContentBlock[];
}

export interface MessageContentBlock {
  type: "text" | "tool_result";
  text?: string;
  tool_use_id?: string;
  content?: string;
}

export interface UnifiedRequest {
  /** Unique identifier for this request, generated by the caller */
  id: string;
  /** Target provider. Must be in guardrails.config.json allowed_providers */
  provider: string;
  /** Target model identifier within the provider */
  model: string;
  /** System prompt. Provider adapters map this to their native system field */
  system?: string;
  /** Conversation messages */
  messages: Message[];
  /** Tool definitions available for this request */
  tools?: ToolDefinition[];
  /** Maximum tokens the provider should generate */
  max_tokens?: number;
  /** Session identifier for cost ledger tracking */
  session_id?: string;
}
